name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Commit built dist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Add compiled dist"
          git push
